name: Deploy to EC2 

on:
  push:
    branches:
      - main     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_PRUEBA }}
          username: ${{ secrets.USER_PRUEBA }}
          key: ${{ secrets.VOCKEY_FILE_PRUEBA }}
          script: |
            sudo yum update -y
            sudo yum install -y nodejs npm git
            sudo rm -rf /opt/Main
            sudo mkdir -p /opt/Main
            cd /opt/Compras
            sudo git clone https://${{ secrets.GH_TOKEN_COMPRAS }}@github.com/GuidoSantiagoReta/prueba-ami .
            sudo npm install express 
            sudo npm install -g pm2
            sudo pm2 start app.js
            sudo pm2 status
